### ISSUE TITLE
Typo in description

### ISSUE THREAD

**Issue by rizwan95** [younatics/Highlighter#1]
You have a typo in your Readme description. You have written it as Highligher whereas it must be Highlighter. :) 
<img width="834" alt="screen shot 2017-05-06 at 12 19 48 am" src="https://cloud.githubusercontent.com/assets/10910174/25759576/bd111c46-31f0-11e7-93c0-8505d1f98fe4.png">

**Comment by younatics** [comment]
Thanks!
